# Generated by Django 5.0.1 on 2024-01-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=100)),
                ('review_count', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('description', models.TextField()),
                ('promotion', models.DecimalField(decimal_places=0, max_digits=3)),
                ('marque', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(to='product.category')),
            ],
        ),
    ]
